version: '3.8'

services:
  postgres:
    image: postgres:15.8-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    ports:
      - "15432:5432"
    volumes:
      - ./unit_test_init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - "16379:6379"
